blog/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/',views.logout, name='logout'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/pwd_change/', views.password_change, name='pwd_change'),
]

blog/blog/urls.py
from django.urls import path, include
from . import views
app_name = 'blog'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.article_list, name='list'),
    path('article/<int:article_id>.html', views.detail, name='detail'),
    path('archives/<int:year>/',views.year_archives, name='year_archives'),
    path('archives/<int:year>/<int:month>/',views.mouth_archives, name='month_archives'),
    path('tag/<str:tag_name>.html',views.tag_article, name='tag'),
]

blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('blog.urls', namespace='blog')),
    path(r'comment/', include('comments.urls', namespace='comments')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
    # path(r'', include('blog.urls', namespace='blog')),
]

blog/blog/models.py
# coding: utf-8
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


# Create your models here.
class Article(models.Model):
    """文章"""
    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表'),
    )
    COMMENT_STATUS = (
        ('o', '打开'),
        ('c', '关闭'),
    )
    TYPE = (
        ('a', '文章'),
        ('p', '页面'),
    )
    title = models.CharField('标题', max_length=200, unique=True)
    # body = MDTextField('正文')
    body = models.TextField('正文')
    pub_time = models.DateTimeField('发布时间', default=now)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES, default='p')
    comment_status = models.CharField('评论状态', max_length=1, choices=COMMENT_STATUS, default='o')
    type = models.CharField('类型', max_length=1, choices=TYPE, default='a')
    views = models.PositiveIntegerField('浏览量', default=0)
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    author = models.CharField('作者', max_length=200)
    article_order = models.IntegerField('排序,数字越大越靠前', blank=False, null=False, default=0)
    # category = models.ForeignKey('Category', verbose_name='分类', on_delete=models.CASCADE, blank=False, null=False)
    # category = models.CharField('分类', max_length=200)
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'article_id': self.id})

    def viewd(self):
        self.views += 1
        self.save(update_fields=['views'])

# class Category(models.Model):
#     name = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

blog/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.conf import settings
from blog.models import Article, Tag
from django.utils.html import strip_tags
from django.shortcuts import get_list_or_404
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import markdown


class IndexView(ListView):
    template_name = "blog/index.html"
    context_object_name = 'article_list'
    model = Article


def article_list(request):
    a_list = Article.objects.all().order_by('-pub_time')
    # for article in a_list:
    #     article.body = md.convert(article.body)
    #     article.body = strip_tags(article.body)[:300]
    cut_md_article(a_list)
    right_archives = get_archives()
    return render(request, 'blog/index.html',
                  context={'tags': Tag.objects.all(), 'article_list': a_list, 'archives': right_archives})


def detail(request, article_id):
    article_detail = Article.objects.filter(id=article_id).first()
    article_detail.viewd()
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    article_detail.body = md.convert(article_detail.body)
    comment_list = article_detail.comment_set.filter(parent__isnull=True).order_by('-pub_time')
    paginator = Paginator(comment_list, 5)
    contacts = paginator.page(1)

    content = {
        'tags': Tag.objects.all(),
        'article': article_detail,
        "toc": md.toc_tokens,
        # 'comment_list': comment_list,
        'contacts':contacts,
        "curr_article_id": article_id,
    }
    return render(request, 'blog/detail.html', context=content)


def year_archives(request, year):
    year_article = Article.objects.filter(pub_time__year=year).order_by('-pub_time')
    # for article in year_article:
    #     article.body = md.convert(article.body)
    #     article.body = strip_tags(article.body)[:300]
    cut_md_article(year_article)
    right_archives = get_archives()
    return render(request, 'blog/index.html',
                  context={'tags': Tag.objects.all(), 'article_list': year_article, 'archives': right_archives})


def mouth_archives(request, year, month):
    month_article = Article.objects.filter(pub_time__year=year, pub_time__month=month).order_by('-pub_time')
    cut_md_article(month_article)
    right_archives = get_archives()
    return render(request, 'blog/index.html',
                  context={'tags': Tag.objects.all(), 'article_list': month_article, 'archives': right_archives})


def tag_article(request, tag_name):
    articles_tags = Tag.objects.get(name=tag_name).article_set.all()
    cut_md_article(articles_tags)
    return render(request, 'blog/index.html',
                  context={'tags': Tag.objects.all(), 'article_list': articles_tags, 'archives': get_archives()})


def get_archives():
    article_list = Article.objects.all().order_by("pub_time")
    res = {}
    for article in article_list:
        article.pub_time = timezone.localtime(article.pub_time)
        year = article.pub_time.year
        month = article.pub_time.month
        if year not in res.keys():
            res[year] = {month: 1}
        elif month not in res[year].keys():
            res[year][month] = 1
        else:
            res[year][month] += 1
    return res


def cut_md_article(article_list):
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    for article in article_list:
        article.body = md.convert(article.body)
        article.body = strip_tags(article.body)[:100]

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>{% block title %}base.html{% endblock title %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/blog.css">
    <link rel="stylesheet" href="/static/css/github.css">
    <script src="/static/js/jquery-3.4.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>


</head>
<body data-spy="scroll" data-target="#right_nav">

<div class="navbar navbar-default navbar-static-top" id="top">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#dh">

                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand"><strong>鸽</strong></a>
        </div>
        <div class="collapse navbar-collapse" id="dh">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/">Posts</a>
                </li>
                <li>
                    <a href="/about.html">About</a>
                </li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" value="搜索..."/>
                        <span class="input-group-btn">
                            <button class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="container" id="content">
        <h1>Tags</h1>
        <h3>
            {% for tag in tags %}
                <span class="label label-success"><a href="{% url 'blog:tag' tag.name %}">{{ tag.name }}</a></span>
            {% endfor %}
        </h3>

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs12" id="main">
            {% block main %}
                没有数据
            {% endblock main %}
        </div>
        <div class="col-lg-3 col-md-3  hidden-sm hidden-xs" id="right_menu">
            {% block right_menu %}
                没有数据
            {% endblock right_menu %}
        </div>
    </div>
</div>


<footer class="panel-footer">
    <h3>footer</h3>
</footer>
</body>
<script src="/static/js/blog.js"></script>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block title %}detail{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-xs-12" id="article_info" data-id="{{ article.id }}">
            <h2>{{ article.title }}</h2>

            <span class="text-right date-author-views">{{ article.pub_time|date:"Y-m-d" }} / {{ article.author }} / {{ article.views }}views</span>

        </div>
        <div class="col-xs-12">{{ article.body | safe }}</div>
        <div class="col-xs-12">
            <div class="alert alert-danger hidden" role="alert" id="result">评论失败！</div>
        </div>
        <div class="col-xs-12">
            <div class="page-header">
                <h1>评论：
                    {% if request.user.is_authenticated %}
                        <small class="pull-right">current_user：
                            <a href="{% url 'accounts:profile' request.user.id %}"
                               id="toModify">{{ request.user.username }}</a>
                        </small>
                    {% endif %}
                </h1>
                {% if request.user.is_authenticated %}
                    <div class="modal fade" id="modify_modal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">你的信息：</div>
                                <div class="modal-body">
                                    <ul class="nav">
                                        <li>username: {{ request.user.username }}</li>
                                        <li>email: {{ request.user.email }}</li>
                                    </ul>
                                </div>
                                <div class="modal-footer">
                                    <button href="{% url 'accounts:pwd_change' request.user.id %}"
                                            class="btn btn-primary" id="toPwdChange">Change Passwrd
                                    </button>
                                    <button class="btn btn-primary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-xs-12">
            {% if request.user.is_authenticated %}
                {% include 'comments/comment_form.html' %}
            {% else %}
                <div class="alert alert-danger" role="alert">
                    请先<a id="toLogin">登录</a>后发表评论。没有账号欢迎 <a id="toReg">注册</a>
                </div>
                {#.modal>.modal-dialog>.modal-content>.modal-header+.modal-body+.modal-footer#}
                <div class="modal fade" id="login_modal">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">请登录</div>
                            <div class="modal-body"></div>
                            <div class="modal-footer">
                                <button class="btn btn-primary" id="login_submit">Login</button>
                                <button class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="reg_modal">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">请注册</div>
                            <div class="modal-body"></div>
                            <div class="modal-footer">
                                <button class="btn btn-primary" id="reg_submit">Register</button>
                                <button class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="col-xs-12" id="comment_list">
            {% include 'comments/comment_list.html' %}
        </div>
    </div>
{% endblock main %}

{% block right_menu %}
    <div class="affix" data-spy="affix" data-offset-top="150" data-offset-bottom="160" id="right_nav">
        <ul class="nav scrollspy">
            {% for l1 in toc %}
                <li>
                    <a href="#{{ l1.id }}">{{ l1.name }}</a>
                    {% for l2 in l1.children %}
                        <ul class="nav">
                            <li>
                                <a href="#{{ l2.id }}">{{ l2.name }}</a>
                                {% for l3 in l2.children %}
                                    <ul class="nav">
                                        <li>
                                            <a href="#{{ l3.id }}">{{ l3.name }}</a>
                                        </li>
                                    </ul>
                                {% endfor %}
                            </li>
                        </ul>
                    {% endfor %}
                </li>
            {% endfor %}
            <li>
                <a class='back-to-top' href="#top">返回顶部</a>
            </li>
        </ul>

    </div>
{% endblock right_menu %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}主页{% endblock %}
{% block main %}
    {% for article in article_list %}
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title"><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h1>
                </div>
                <div class="panel-body">
                    <p class="lead">{{ article.body }}</p>
                </div>
                <div class="panel-heading clearfix">
                    <div class="article_info pull-left">
                        {{ article.author }} / {{ article.pub_time |date:"Y-m-d" }}
                        {% for t in article.tags.all %}
                            / {{ t.name }}
                        {% endfor %}
                    </div>
                    <div class="article_info pull-right">{{ article.views }} views</div>
                </div>
            </div>
        </div>
    {% empty %}
        <h2>无数据</h2>
    {% endfor %}
{% endblock main %}
{% block right_menu %}
    <ul class="list-group">
        {% for year,d_month in archives.items %}
            <li class="list-group-item"><a href="{% url 'blog:year_archives' year %}">{{ year }}</a></li>
            <ul>
                {% for month,count in d_month.items %}
                    <li class="list-group-item"><a href="{% url 'blog:month_archives' year month %}">{{ month }}月</a>
                        <span class="badge">{{ count }}</span>
                    </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>

{% endblock right_menu %}