blog/blog/urls.py
from django.urls import path, include
from . import views
app_name = 'blog'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.article_list, name='list'),
    path('article/<int:article_id>.html', views.detail, name='detail'),
    path('archives/<int:year>/',views.year_archives, name='year_archives'),
    path('archives/<int:year>/<int:month>/',views.mouth_archives, name='month_archives'),
    path('tag/<str:tag_name>.html',views.tag_article, name='tag'),
]

blog/comments/urls.py
from django.urls import path
from comments import views
app_name = 'comments'
urlpatterns = [
    path('post/<int:article_id>/',views.post_comment, name='post_comment'),
    path('def/<int:comment_id>/',views.del_comment, name='del_comment'),
    path('page/<int:article_id>/<int:page>/', views.page_comment, name='page_comment'),
]

blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('blog.urls', namespace='blog')),
    path(r'comment/', include('comments.urls', namespace='comments')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
    # path(r'', include('blog.urls', namespace='blog')),
]

blog/comments/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from blog.models import Article


# Create your models here.


class Comment(models.Model):
    text = models.TextField('内容', max_length=300)
    pub_time = models.DateTimeField('评论时间', default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name="评论人", on_delete=models.CASCADE)
    parent = models.ForeignKey('self', verbose_name="父评论", blank=True,null=True, on_delete=models.CASCADE)
    is_delete = models.BooleanField('是否删除',default=False,)

    def __str__(self):
        return self.text

blog/comments/forms.py
from django import forms
from .models import Comment


class CommentsForm(forms.ModelForm):
    parent = forms.IntegerField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Comment
        fields = ['text']

blog/comments/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from comments.models import Comment
from blog.models import Article
from comments.forms import CommentsForm
from django.http import JsonResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from accounts.models import BlogUser
from django.utils import timezone


# Create your views here.

def post_comment(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    if not request.user.is_authenticated:
        return JsonResponse({'code': 2, 'message': '你还没有登陆'})

    if request.method == "POST":
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(False)
            comment.article = article
            if request.POST['parent'] != '-1':
                parent = Comment.objects.get(id=request.POST['parent'])
                comment.parent = parent
            comment.author = request.user
            comment.save()
            comment.pub_time = timezone.localtime(comment.pub_time)
            res = {
                'code': 1,
                'message': '评论成功',
                'cur_comment': {
                    'cid': comment.id,
                    'ctext': comment.text,
                    'ctime': comment.pub_time.strftime('%Y-%m-%d %H:%M'),
                    'cparent': comment.parent_id,
                    'uid': comment.author.id,
                    'uname': comment.author.username,
                },
            }
            return JsonResponse(res)
        else:
            return JsonResponse({'code': 0, 'message': '数据验证错误，评论失败'})

    return JsonResponse({'code': 0, 'message': 'method错误，评论失败'})


def del_comment(request, comment_id):
    filter_comment = Comment.objects.filter(id=comment_id)
    if len(filter_comment) > 0:
        filter_comment.delete()

    return HttpResponseRedirect(request.path)


def page_comment(request, article_id, page):
    comment_list = Article.objects.filter(id=article_id).first().comment_set.filter(
        parent__isnull=True).order_by('-pub_time')
    paginator = Paginator(comment_list, 5)
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # 如果用户请求的页码号不是整数，显示第一页
        contacts = paginator.page(1)
    except EmptyPage:
        # 如果用户请求的页码号超过了最大页码号，显示最后一页
        contacts = paginator.page(paginator.num_pages)
    return render(request, 'comments/comment_list.html', {"contacts": contacts, "curr_article_id": article_id})

blog/templates/comments/comment_form.html
<div class="comments-form row">
    <form action="{% url 'comments:post_comment' article.id %}" id="commentForm">
        <div class="col-xs-1"><img class="img-circle" src="/static/img/tako.jpg" alt="..."></div>

        <div class="col-xs-10">
            <textarea name="text" id="" cols="80" rows="5" class="text-txt"
                      placeholder="请自觉遵守互联网相关的政策法规，严禁发布色情、暴力、反动的言论。" ></textarea>
            {% csrf_token %}
        </div>
        <div class="col-xs-1">
            <button type="submit" class="mybtn" id="postComment">发表评论</button>
        </div>
    </form>

</div>

blog/templates/comments/comment_list.html
{% if contacts %}

    <div class="comments-content">
        {% for comment in contacts.object_list %}
            {% if not comment.parent %}
                <div class="media" data-id="{{ comment.id }}">
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object img-circle" src="/static/img/tako.jpg"
                                 alt="{{ comment.author.username }}">
                        </a>
                    </div>
                    <div class="media-body">
                        <p class="media-heading" user-id="{{ comment.author.id }}">
                            <a href="#">{{ comment.author.username }}</a>
                        </p>
                        <p id="ctext">{{ comment.text }}</p>
                        <p class="media-heading ">
                            <span>{{ comment.pub_time|date:"Y-m-d H:i" }}</span>
                            <a comm_id="{{ comment.id }}" class="showSubCommentForm">回复</a>
                            {% if comment.author.id == request.user.id %}
                                <a class="pull-right" href="{% url 'comments:del_comment' comment.id %}"
                                   id="delComment">删除</a>
                            {% endif %}
                        </p>
                        {% for sub_comment in  comment.comment_set.all %}
                            <div class="media" data-id="{{ sub_comment.id }}">
                                <div class="media-left">
                                    <a href="#">
                                        <img class="media-object img-circle" style="max-width: 45px;max-height: 45px"
                                             src="/static/img/tako.jpg" alt="{{ sub_comment.author.username }}">
                                    </a>
                                </div>
                                <div class="media-body">
                                    <p class="media-heading" user-id="{{ sub_comment.author.id }}">
                                        <a href="#">{{ sub_comment.author.username }}</a>:
                                        {{ sub_comment.text }}
                                    </p>
                                    <p class="media-heading">
                                        <span>{{ sub_comment.pub_time|date:"Y-m-d H:i" }}</span>
                                        <a comm_id="{{ sub_comment.id }}" parent_id="{{ comment.id }}"
                                           class="showSubCommentForm">回复</a>
                                        {% if sub_comment.author.id == request.user.id %}
                                            <a class="pull-right" href="{% url 'comments:del_comment' sub_comment.id %}"
                                               id="delComment">删除</a>
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="media hidden" id="sub_content_{{ comment.id }}"></div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <nav>
        <ul class="pager">
            {% if contacts.has_previous %}
                <li class="previous"><a href="{% url 'comments:page_comment' curr_article_id contacts.previous_page_number %}" class="load_page"><span
                        aria-hidden="true">&larr;</span> Previous</a></li>
            {% else %}
                <li class="previous disabled"><a><span aria-hidden="true">&larr;</span> Previous</a></li>
            {% endif %}
            {% if contacts.has_next %}
                <li class="next"><a href="{% url 'comments:page_comment' curr_article_id contacts.next_page_number %}" class="load_page">Next <span
                        aria-hidden="true">&rarr;</span></a>
                    {% else %}
                <li class="next disabled"><a>Next <span aria-hidden="true">&rarr;</span></a>
            {% endif %}
            </li>
        </ul>
    </nav>
{% else %}
    <div class="page-header"><h1>没有更多信息 </h1></div>
{% endif %}